name = "todo-schedules"
compatibility_date = "2024-01-01"

# D1 資料庫配置
[[d1_databases]]
binding = "DB"
database_name = "todo-schedules"
database_id = "6598209a-a0c6-4daf-b59b-a1f185c2778b"

# Pages 配置
[pages]
directory = "."

# 環境變數（如果需要）
[vars]
ENVIRONMENT = "production"
